import { Observable } from 'rxjs/Observable'

import 'rxjs/add/observable/empty'
import 'rxjs/add/observable/of'
import 'rxjs/add/observable/merge'
import 'rxjs/add/observable/combineLatest'
import 'rxjs/add/observable/timer'
import 'rxjs/add/observable/fromEvent'

import 'rxjs/add/operator/filter'
import 'rxjs/add/operator/map'
import 'rxjs/add/operator/mapTo'
import 'rxjs/add/operator/withLatestFrom'
import 'rxjs/add/operator/merge'
import 'rxjs/add/operator/catch'
import 'rxjs/add/operator/startWith'
import 'rxjs/add/operator/mergeMap'
import 'rxjs/add/operator/scan'
import 'rxjs/add/operator/combineLatest'
import 'rxjs/add/operator/share'
import 'rxjs/add/operator/throttleTime'
import 'rxjs/add/operator/switchMap'
import 'rxjs/add/operator/distinctUntilChanged'
import 'rxjs/add/operator/first'
import 'rxjs/add/operator/skip'
import 'rxjs/add/operator/concat'
import 'rxjs/add/operator/pluck'
import 'rxjs/add/operator/delay'
import 'rxjs/add/operator/shareReplay'

module.exports = { Observable }
